spring.application.name=user-service
server.port=8081

# Database configuration
spring.datasource.name=user_service
spring.datasource.url=jdbc:mysql://mysql-75e4481-premmakwana555.c.aivencloud.com:10277/user_service_db
spring.datasource.username=mysql_user
spring.datasource.password=mysql_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=false
spring.flyway.validate-on-migrate=true

# Custom properties
token.expiry=10
